[sections]

[sections.I1]
start_name1 = "STSEC.23.I1"
stop_name1 = "ENSUB.62.I1"

[sections.I1.new_markers]
"stop_astra" = {s = 3.2} # If current S is more than this s, append this first and then consume
"start_ocelot" = {s = 3.2}
"a1_sim_stop" = {ref="C.A1.1.8.I1", location = "after"} # If previous element was this elemnet, append and then consume a
"ah1_sim_start" = {ref="C.A1.1.8.I1", location = "after"}
"a1_1_stop" = {ref="C.A1.1.1.I1", location = "after"}
"lh_start" = {ref="U74.49.I1", location="before"} # If current element is this element, then append and consume
"lh_stop" = {ref="U74.49.I1", location="after"}
# "DUMP.CSR.START" = {ref='ENSUB.62.I1', delta_s=-0.1}
"DUMP.CSR.START" = {s = 38.789005}

[sections.I1D]
start_name1 = "STSEC.62.I1D"
stop_name1 = "ENSEC.66.I1D"

[sections.L1]
start_name1 = "STSUB.62.I1"
stop_name1 = "ENSUB.229.B1"

[sections.L1.new_markers]
dogleg_start = { ref='CIX.65.I1', location = "before"}
dogleg_stop_bc0_start = { ref = "STLAT.96.I1", location = "before" }
bc0_stop_l1_start = { ref = "QI.103.I1", location = "before" }
l1_stop_bc1_start = { ref = "STLAT.182.B1", location= "before" }
bc1_stop_l2_start = { ref = "TORA.203.B1", location = "after" }


[sections.B1D]
start_name1 = "STSEC.229.B1D"
stop_name1 = "ENSEC.237.B1D"

[sections.L2]
start_name1 = "STSUB.229.B1"
stop_name1 = "ENSUB.466.B2"

[sections.L2.new_markers]
l2_stop_bc2_start = { ref = "STLAT.393.B2", location = "before" }
bc2_stop_b2d_start = { ref = "TORA.415.B2", location = "after" }

[sections.B2D]
start_name1 = "STSEC.466.B2D"
stop_name1 = "ENSEC.480.B2D"

[sections.L3]
start_name1 = "STSUB.466.B2"
stop_name1 = "ENSEC.1652.L3"

[sections.L3.new_markers]
stop_l3 = { ref = "CFY.1651.L3", location = "before"}

[sections.CL]
start_name1 = "STSEC.1652.CL"
stop_name1 = "ENSUB.1980.TL"

[sections.TLD]
start_name1 = "STSEC.1980.TLD"
stop_name1 = "ENSEC.2130.TLD"

# [sections.TL3TL4]
# start_name1 = "STSUB.1980.TL"
# stop_name1 = "ENSUB.2025.TL"

# [sections.sa1]
# start_name1 = "STSUB.2025.TL"
# stop_name1 = "ENSEC.2461.SA1"

# [sections.t4]
# start_name1 = "STSEC.2461.T4"
# stop_name1 = "ENSUB.2800.T4"

# [sections.sa3]
# start_name1 = "STSEC.2800.T4"
# stop_name1 = "ENSEC.2955.SA3"

# [sections.t4d]
# start_name1 = "STSEC.2955.T4D"
# stop_name1 = "ENSEC.3106.T4D"

[extras.design]
[extras.design."TDSA.52.I1"]
tilt = 1.570796327

[extras.design."U74.49.I1"]
nperiods = 10

[extras.real]
[extras.real.components."U74.49.I1"]
Kx = 1.315
Ky = 0.0


# [processes.csr.lh]
# start = "Asdasd"
# stop = "asdasd"
# sigma_min = 0.55

# [extras.real.hlc.LH]
# angle = 5.7 deg
# r56 = -4.34mm

# [extras.real.hlc.BC0]
# -6.85
# -50mm

# [extras.real.hlc.BC1]
# -2.86
# -50.11mm

# [extras.real.hlc.BC2]
# -2.39
# r56 = -29.97mm

# [extras.real.tracking]
